### ISSUE TITLE
Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by kchodorow** [plaid/plaid-python#111]
My code is calling `plaid_client.Transactions.get(token, self._start_date, self._end_date, offset=len(transactions))` which mostly has been working great but occasionally throws the following error:

```
Dec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.948010 2017] [:error] [pid 12503] An error occurred while resolving field Mutation.sync
Dec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.950807 2017] [:error] [pid 12503] Traceback (most recent call last):
Dec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.950824 2017] [:error] [pid 12503] File "/opt/python/run/venv/local/lib/python3.4/site-packages/graphql/execution/executor.py", line 311, in resolve_or_error
Dec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.950835 2017] [:error] [pid 12503] return executor.execute(resolve_fn, source, info, **args)
Dec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.950845 2017] [:error] [pid 12503] File "/opt/python/run/venv/local/lib/python3.4/site-packages/graphql/execution/executors/sync.py", line 7, in execute
Dec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.950855 2017] [:error] [pid 12503] return fn(*args, **kwargs)
Dec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.950865 2017] [:error] [pid 12503] File "/opt/python/current/app/moirai/gql/sync.py", line 23, in mutate
Dec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.950874 2017] [:error] [pid 12503] state = record.store_transactions(access_token)
Dec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.950885 2017] [:error] [pid 12503] File "/opt/python/current/app/moirai/db/user_record.py", line 43, in store_transactions
Dec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.950894 2017] [:error] [pid 12503] token=access_token, since=last_updated)
Dec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.950904 2017] [:error] [pid 12503] File "/opt/python/current/app/moirai/db/plaid_connection.py", line 48, in get_transactions_and_accounts
Dec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.950914 2017] [:error] [pid 12503] return self._get_transactions(token=token, since=since)
Dec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.950934 2017] [:error] [pid 12503] response = self._client.Transactions.get(token, START_DATE, self._end_date, offset=len(transactions))
Dec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.950944 2017] [:error] [pid 12503] File "/opt/python/run/venv/local/lib/python3.4/site-packages/plaid/api/transactions.py", line 49, in get
Dec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.950954 2017] [:error] [pid 12503] "options": options,
Dec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.950963 2017] [:error] [pid 12503] File "/opt/python/run/venv/local/lib/python3.4/site-packages/plaid/client.py", line 83, in post
Dec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.950973 2017] [:error] [pid 12503] return self._post(path, post_data)
Dec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.950983 2017] [:error] [pid 12503] File "/opt/python/run/venv/local/lib/python3.4/site-packages/plaid/client.py", line 101, in _post
Dec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.950993 2017] [:error] [pid 12503] timeout=self.timeout
Dec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.951002 2017] [:error] [pid 12503] File "/opt/python/run/venv/local/lib/python3.4/site-packages/plaid/requester.py", line 33, in http_request
Dec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.951012 2017] [:error] [pid 12503] response_body = json.loads(response.text)
Dec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.951021 2017] [:error] [pid 12503] File "/usr/lib64/python3.4/json/__init__.py", line 318, in loads
Dec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.951031 2017] [:error] [pid 12503] return _default_decoder.decode(s)
Dec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.951040 2017] [:error] [pid 12503] File "/usr/lib64/python3.4/json/decoder.py", line 343, in decode
Dec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.951050 2017] [:error] [pid 12503] obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Dec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.951060 2017] [:error] [pid 12503] File "/usr/lib64/python3.4/json/decoder.py", line 361, in raw_decode
Dec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.951069 2017] [:error] [pid 12503] raise ValueError(errmsg("Expecting value", s, err.value)) from None
Dec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.951084 2017] [:error] [pid 12503] ValueError: Expecting value: line 1 column 1 (char 0)
Dec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.951105 2017] [:error] [pid 12503]
Dec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.957345 2017] [:error] [pid 12503] Traceback (most recent call last):
Dec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.957380 2017] [:error] [pid 12503] File "/opt/python/run/venv/local/lib/python3.4/site-packages/graphql/execution/executor.py", line 330, in complete_value_catching_error
Dec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.957856 2017] [:error] [pid 12503] exe_context, return_type, field_asts, info, result)
Dec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.957885 2017] [:error] [pid 12503] File "/opt/python/run/venv/local/lib/python3.4/site-packages/graphql/execution/executor.py", line 383, in complete_value
Dec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.958301 2017] [:error] [pid 12503] raise GraphQLLocatedError(field_asts, original_error=result)
Dec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.958356 2017] [:error] [pid 12503] graphql.error.located_error.GraphQLLocatedError: Expecting value: line 1 column 1 (char 0)
```

Plaid is trying to call `json.loads` on `response.text`, which is apparently ''. 

I'm using plaid-python version 2.0.2.

**Comment by joyzheng** [comment]
hey @kchodorow -- thanks for reporting! the empty response was due to a server bug that has since been fixed. 

We also added better handling of invalid json responses in #108, which translates invalid json into errors with code `PLAID_ERROR`. Can you please try upgrading to the latest library version (v2.1.1) to pick up that change? Feel free to reopen this issue if you're still running into problems.

**Comment by kchodorow** [comment]
Thanks for the update! Will do.
