### ISSUE TITLE
TypeError: can only concatenate str (not "NoneType") to str

### ISSUE THREAD

**Issue by spencerlawrence36** [plaid/plaid-python#192]
Hello, I'm just getting started with the Plaid API.  I've set my environment variables and confirmed they work fine.

Code: 
```
import os
from plaid import Client as PlaidClient

plaid_client = PlaidClient(client_id=os.getenv('PLAID_CLIENT_ID'), secret=os.getenv('PLAID_SECRET'),
                           public_key=os.getenv('PLAID_PUBLIC_ID'), environment=os.getenv('PLAID_ENV'))

def get_some_transactions(access_token, start_date, end_date):
    return plaid_client.Transactions.get(access_token, start_date, end_date)

some_transactions = get_some_transactions(os.getenv('CHASE_ACCESS_TOKEN'), '2019-12-01', '2019-12-23')
print(some_transactions['total_transactions'])
```

Output:
```Traceback (most recent call last):
  File "get_transactions.py", line 12, in <module>
    some_transactions = get_some_transactions(os.getenv('CHASE_ACCESS_TOKEN'), '2019-12-01', '2019-12-23')
  File "get_transactions.py", line 10, in get_some_transactions
    return plaid_client.Transactions.get(access_token, start_date, end_date)
  File "/usr/local/lib/python3.7/site-packages/plaid/api/transactions.py", line 49, in get
    'options': options,
  File "/usr/local/lib/python3.7/site-packages/plaid/client.py", line 98, in post
    return self._post(path, post_data, is_json)
  File "/usr/local/lib/python3.7/site-packages/plaid/client.py", line 119, in _post
    urljoin('https://' + self.environment + '.plaid.com', path),
TypeError: can only concatenate str (not "NoneType") to str
```

Note that I am using Python 3.7.5.  Is this an issue with Python versioning?  Not sure how to debug from this point. 

Thanks

**Comment by blackmarkt** [comment]
I encountered this and my solution was to make the environment variables persistently available using dotenv.

**Comment by davidzhanghp** [comment]
Hi @spencerlawrence36 were you able to make it work?

**Comment by spencerlawrence36** [comment]
@davidzhanghp - unfortunately not.  I had issues with dotenv but it may work for others.
