### ISSUE TITLE
link_token_create() results in a cascade of errors

### ISSUE THREAD

**Issue by MichaelSternNYC** [plaid/plaid-python#382]
Updating some (python) code and I find that I can not even get a link token, generating a cascading series of errors that starts with

Traceback (most recent call last):
File "/usr/local/lib/python3.7/dist-packages/urllib3/connection.py", line 175, in _new_conn
(self._dns_host, self.port), self.timeout, **extra_kw
File "/usr/local/lib/python3.7/dist-packages/urllib3/util/connection.py", line 73, in create_connection
for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

In debugging I even swapped in your own python code for getting a link token from 
https://plaid.com/docs/api/tokens/

1. I think your sample code is missing a comma after the account_filters assignment, and
2. that fixed, I get the exact same error above.

We are using the correct clientID but crashes when I call client.link_token_create().

**Comment by MichaelSternNYC** [comment]
Never mind, user error.
